name: C CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Compile
      run: gcc -o test_math sources/math.c sources/test_math.c

    - name: Run Tests
      run: ./test_math